<?php


namespace App\Model;


class MatchManager extends AbstractManager
{

    /**
     * Created by PhpStorm.
     * User: sylvain
     * Date: 07/03/18
     * Time: 18:20
     * PHP version 7
     */

    const TABLE = 'characters';

    /**
     *  Initializes this class.
     */
    public function __construct()
    {
        parent::__construct(self::TABLE);
    }

    public function selectAll(): array
    {
        return parent::selectAll(); // TODO: Change the autogenerated stub
    }

    public function selectMatch()
    {
        return $this->pdo->query('SELECT id, name, loveStyle, food, ethic, partyMonster, matchRate FROM ' . $this->table)->fetchAll();

    }

    public function addMatch(int $totalMatch, int $id)
    {
        $request = $this->pdo->prepare("UPDATE " .self::TABLE.  " SET matchRate =  ". $totalMatch. " WHERE id=".$id);
        $request->execute();
    }

    public function selectByMatch()
    {
        return $this->pdo->query("SELECT * FROM " .self::TABLE. " ORDER BY matchRate DESC")->fetchAll();
    }
}